name: Build on master schedule

on:
  schedule:
  - cron: "0 2 15 * *"

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Run Docker buildx for master
        run: |
          docker buildx build \
          --platform linux/386,linux/ppc64le \
          --file ./Dockerfile \
          --build-arg GIT_TAG=master \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/gotty:dev \
          --push .
          
      - name: Run Docker buildx for master
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
          --file ./Dockerfile \
          --build-arg GIT_TAG=master \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/gotty:latest \
          --push .
